---
- name: Debug variables
  hosts: all
  tags: debug
  tasks:
    - ansible.builtin.debug:
        msg: "Secrets: {{ _secrets | to_yaml }}"

- name: Debug write groups['dela_nodes']
  hosts: all
  tags: debug
  tasks:
    - ansible.builtin.debug:
        msg: "{{ groups['dela_nodes'] }}"

- name: System
  hosts: all
  # gather_facts: no
  roles: 
    - name: setup common system requirements
      role: roles/system

- name: D-voting Dela Worker Nodes
  hosts: dela_nodes
  roles:
    - name: ensure traefik container
      role: roles/traefik
    - name: setup dela demo
      role: roles/dela_node

- name: D-voting web front/backend
  hosts: dvoting_web
  roles:
    - name: dvoding web server
      role: roles/dvoting
    - name: ensure traefik container
      role: roles/traefik
