---
- name: Debug variables
  hosts: all
  tags: debug
  tasks:
    - debug:
        msg: "Secrets: {{ _secrets | to_yaml }}"

- name: System
  hosts: all
  # gather_facts: no
  roles: 
    - name: setup common system requirements
      role: roles/system

- name: Demo
  hosts: dela_nodes
  roles:
    - name: ensure traefik container
      role: roles/traefik
    - name: setup dela demo
      role: roles/demo