---
- name: Setup memcoin node
  hosts: devconodes
  gather_facts: no
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - name: Setup conode
      role: roles/conode

- name: Setup front-end
  hosts: devportal
  gather_facts: no
  handlers:
    - import_tasks: handlers/main.yml
  roles:
    - name: Setup portal
      role: roles/portal
