#- name: Clone bill2myprint repo
#  git:
#      repo: https://github.com/dedis/d-voting.git
#      dest: /tmp/d-voting
#      force: yes
#      version: main
#  tags:
#    - git_clone


#- name: Recursively change ownership of a directory
#  ansible.builtin.file:
#    path: /app/ofrf/src
#    recurse: yes
#    mode: '0755'
#  become: yes
#  tags:
#    - ofrf_change_modea


- name: source tar.gz exists ?
  ansible.builtin.shell:
    cmd: "test -e v{{ DELA_VERSION }}.tar.gz && echo 'It exists'"
  failed_when: false
  changed_when: false
  register: _source_code_exist


- name: Download source code tar.gz
  ansible.builtin.get_url:
    url: "https://github.com/dedis/d-voting/archive/refs/tags/v{{ DELA_VERSION }}.tar.gz"
    dest: "{{ INSTALL_DIR }}/{{ DELA_VERSION }}.tar.gz"
    mode: '0755'
  tags:
    - download_source_code
  when: _source_code_exist.stdout.find('It exists') == -1


- name: Unzip code source tar.gz version  # tar xvfz v0.4.4.tar.gz
  ansible.builtin.unarchive:
    src: "v{{ DELA_VERSION }}.tar.gz"
    dest: /home/ubuntu
    remote_src: yes
  tags:
    - unzip_source_code
  when: _source_code_exist.stdout.find('It exists') == -1
