---
- name: Last web-frontend tar.gz version exists ?
  shell:
    cmd: "test -e web-frontend-v{{ DELA_VERSION }}.tar.gz && echo 'It exists'"
  failed_when: false
  changed_when: false
  register: _web_frontend_exist


- name: Download last web-frontend tar.gz if not present
  get_url:
    url: "{{ DELA_GITHUB }}v{{ DELA_VERSION }}/web-frontend-v{{ DELA_VERSION }}.tar.gz"
    dest: "{{ INSTALL_DIR }}/web-frontend-v{{ DELA_VERSION }}.tar.gz"
    mode: '0755'
  tags:
    - download_web_frontend
  when: _web_frontend_exist.stdout.find('It exists') == -1


- name: Unzip last web-frontend tar.gz version -> create build directory"  # tar xvfz web-frontend-v{{ DELA_VERSION }}.tar.gz
  unarchive:
    src: "web-frontend-v{{ DELA_VERSION }}.tar.gz"
    dest: "{{ INSTALL_DIR }}"
    remote_src: yes
  tags:
    - unzip_web_frontend
  when: _web_frontend_exist.stdout.find('It exists') == -1
