---
- name: start_dvoting template
  ansible.builtin.template:
    src: start_dvoting.sh
    dest: start_dvoting.sh
    owner: ubuntu
    group: ubuntu
    mode: '0755'


- name: Changing "start_dvoting.sh" as executable
  file: dest=start_dvoting.sh mode=a+x


- name: Move dvoting.service template in /etc/systemd/system
  ansible.builtin.template:
    src: dvoting.service
    dest: /etc/systemd/system/dvoting.service
    owner: root
    group: root
    mode: '0755'
  notify:
    - reload systemctl
    - restart dvoting
  become: true
  tags:
    - install_dvoting_service


- name: Run dvoting
  service:
    name: dvoting
    enabled: yes
    state: started
  become: true
  changed_when: false
  tags:
    - run_dvoting_service


#- name: Execute start_dvoting.sh
#  command: sh start_dvoting.sh
#  changed_when: false