---
- include_vars: dela_vars.yml
  tags: always

# - name: Print variables for demo
#   ansible.builtin.debug:
#     var: DELA_NODES
#     # var: dela 
#     #msg: "dela: {{ dela | to_yaml }}"
#     verbosity: 2
#   tags:
#     - dela

# - name: Include dela config task
#   tags:
#     - dela
#     - dela.config
#   include_tasks:
#     file: config.yml
#     apply:
#       tags:
#         - dela
#         - dela.config

- name: Include dela run task
  tags:
    - dela
    - dela.run
  include_tasks:
    file: run.yml
    apply:
      tags:
        - dela
        - dela.run

- name: Include dela admin task
  tags:
    - dela
  include_tasks:
    file: admin.yml
    apply:
      tags:
        - never

