---
- name: debug groups['dela_nodes'] etc
  ansible.builtin.debug:
    msg: "{{ groups['dela_nodes'] }}"
  tags:
    - never
    - dela.debug

- name: debug dela.nodes
  ansible.builtin.debug:
    msg: "{{ dela.nodes }}"
  tags:
    - never
    - dela.debug

- name: Include dela setup task
  tags:
    - dela
    - dela.setup
  include_tasks:
    file: setup.yml
    apply:
      tags:
        - dela
        - dela.setup

- name: Include dela run task
  tags:
    - dela
    - dela.run
  include_tasks:
    file: run.yml
    apply:
      tags:
        - dela
        - dela.run

- name: Include dela config task
  tags:
    - dela
    - dela.config
  include_tasks:
    file: config.yml
    apply:
      tags:
        - dela
        - dela.config
        - dela.join
        - dela.manual_join

- name: Include dela admin task
  tags:
    - dela.join_preview
    - dela.join
    - dela.manual_join
  include_tasks:
    file: admin.yml
    apply:
      tags:
        - never