---

# - name: Print variables for demo
#   ansible.builtin.debug:
#     msg: "item: {{ item.name }}"
#     verbosity: 2
#   with_items: "{{ dela.nodes }}"
#   tags:
#     - dela

- name: Ensure volumes for dela worker node(s)
  community.docker.docker_volume:
    name: "dela-worker-{{ item.name }}-data"
  with_items: "{{ dela.nodes }}"

- name: Run dela worker node(s)
  community.docker.docker_container:
    name: "dela-worker-{{ item.name }}"
    container_default_behavior: no_defaults
    hostname: "{{ dela.worker_hostname }}"
    image: "{{ dela.worker_image }}"
    env:
      PROXYKEY: "{{ dela.public_key }}"
      PROXYPORT: "{{ item.http_port }}"
      NODEPORT: "{{ item.node_port }}"
      LLVL: info
      PROXY_LOG: info
      NODE_ENV: production
      PUBLIC_URL: "https://{{ item.node_host }}:443"
    restart_policy: 'unless-stopped'
    state: started
    volumes:
      - "dela-worker-{{ item.name }}-data:/data"
    networks:
      - name: traefik
    labels: "{{ labels | from_yaml }}"
  with_items: "{{ dela.nodes }}"
  vars:
    # Ansible only pass to jinja only values and not keys of dictionaries
    # therefore we do it in two steps:
    # 1. create a yaml string as value hece fully processed by jinja 
    # 2. pass it to from_yaml filter
    labels: |
      traefik.http.services.{{ item.name }}_h.loadbalancer.server.port: "{{ item.http_port }}"
      traefik.http.routers.{{ item.name }}_h.rule: Host("{{ item.http_host }}")
      traefik.http.routers.{{ item.name }}_h.service: {{ item.name }}_h
      traefik.http.routers.{{ item.name }}_h.tls: "true"
      traefik.http.services.{{ item.name }}_n.loadbalancer.server.port: "{{ item.node_port }}"
      traefik.http.services.{{ item.name }}_n.loadbalancer.server.scheme: h2c
      traefik.http.routers.{{ item.name }}_n.rule: Host("{{ item.node_host }}")
      traefik.http.routers.{{ item.name }}_n.service: {{ item.name }}_n
      traefik.http.routers.{{ item.name }}_n.tls: "true"
