---
- include_vars: portal_vars.yml
  tags: always


- name: Update apt-get repo and cache
  apt:
    update_cache: yes
  become: true
  tags:
    - sudo_apt_update


- name: Manage nginx
  import_tasks:
    file: nginx.yml
  tags:
    - manage_nginx


- name: Get specified nodejs version
  import_tasks:
    file: get_node.yml
  tags:
    - get_nodejs


- name: Create data directory
  ansible.builtin.file:
    path: "{{ db_dir }}"
    state: directory
    mode: '0755'


- name: Create user database directory
  ansible.builtin.file:
    path: "{{ db_dir }}/dvoting-users"
    state: directory
    mode: '0755'


- name: Install web backend/frontend for version 0.4.4
  import_tasks:
    file: web_old_versions.yml
  tags:
    - install_web
  when: 'DELA_VERSION == "0.4.4"'


- name: Install web backend/frontend for versions >= 0.4.5
  import_tasks:
    file: web_new_versions.yml
  tags:
    - install_web
  when: 'DELA_VERSION != "0.4.4"'


- name: Copy all /build files in /var/www/html
  copy:
    src: "{{ INSTALL_DIR }}/build/"
    dest: /var/www/html/
    remote_src: yes
  become: yes
  tags:
    - move_build_frontend_to_var_www_html


# AddAdmin is idempotent
- name: Add admins
  shell: |
    NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend/dbUtils").addAdmin("data/dvoting-users", 121769)'
    NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend/dbUtils").addAdmin("data/dvoting-users", 128871)'
  changed_when: false
  tags:
    - add_admins


#- name: Add admins
#  shell: |
#    NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend/dbUtils").listEls("data/dvoting-users")'
#    NODE_ENV=production PORT=6000 NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node web-backend/Server.js
#    NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend/dbUtils").addAdmin("data/dvoting-users", 121769)'
#    NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend/dbUtils").addAdmin("data/dvoting-users", 128871)'
#    NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend/dbUtils").addAdmin("data/dvoting-users")'
#    NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend/dbUtils").listEls("data/dvoting-users")'
#    NODE_ENV=production PORT=6000 NODE_PATH=web-backend/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node web-backend/Server.js



# TODO: explore the solution PM2 : https://pm2.keymetrics.io/
- name: Move voting_portal.service template in /etc/systemd/system
  ansible.builtin.template:
    src: voting_portal.service
    dest: /etc/systemd/system/voting_portal.service
    owner: root
    group: root
    mode: '0755'
  notify:
    - reload systemctl
    - restart portal
  become: true
  tags:
    - install_server_service


- name: Run server.js template
  service:
    name: voting_portal
    enabled: yes
    state: started
  become: true
  tags:
    - run_server_service
