---
- include_vars: portal_vars.yml
  tags: always


#- name: Update apt
#  apt: update_cache=yes
#  become: yes


- name: Manage nginx
  import_tasks:
    file: nginx.yml
  tags:
    - manage_nginx


- name: last node tar.xz version present ?
  ansible.builtin.shell:
    cmd: test -e node-{{ NODE_VERSION }}-linux-x64.tar.xz && echo 'It exists'
  failed_when: false
  changed_when: false
  tags:
    - check_nodejs
  register: _nodejs_exist

- name: Download last linux node tar.xz version
  ansible.builtin.get_url:
    url: "https://nodejs.org/dist/{{ NODE_VERSION }}/node-{{ NODE_VERSION }}-linux-x64.tar.xz"
    dest: "{{ INSTALL_DIR }}/node-{{ NODE_VERSION }}-x64.tar.gz"
    mode: '0755'
  tags:
    - download_nodejs
  when: _nodejs_exist.stdout.find('It exists') == -1

- name: Unzip last node tar.gz version # tar -xvf node-{{ NODE_VERSION }}-linux-x64.tar.gz
  ansible.builtin.unarchive:
    src: "node-{{ NODE_VERSION }}-x64.tar.gz"
    dest: "{{ INSTALL_DIR }}"
    remote_src: yes
  tags:
    - unzip_nodejs
  when: _nodejs_exist.stdout.find('It exists') == -1


- name: Install web backend
  import_tasks:
    file: web_backend.yml
  tags:
    - install_web_backend


## Useless, since all environment variables are set directly in voting_portal.service
#
#- name: Create config.env
#  ansible.builtin.template:
#    src: config.env
#    dest: "web-backend-{{ DELA_VERSION }}/config.env"
#    owner: ubuntu
#    group: ubuntu
#    mode: '0755'
#  tags:
#    - create_config_env


# TODO: explore the solution PM2 : https://pm2.keymetrics.io/
- name: Move voting_portal.service template in /etc/systemd/system
  ansible.builtin.template:
    src: voting_portal.service
    dest: /etc/systemd/system/voting_portal.service
    owner: root
    group: root
    mode: '0755'
  notify:
    - reload systemctl
    - restart portal
  become: true
  tags:
    - install_server_service


- name: Run server.js template
  service:
    name: voting_portal
    enabled: yes
    state: started
  become: true
  tags:
    - run_server_service


- name: Install web frontend
  import_tasks:
    file: web_frontend.yml
  tags:
    - install_web_frontend
