---
- name: Install nginx
  apt:
    name: nginx
    state: present
    force_apt_get: yes
  become: yes


- name: Remove default nginx config (created by nginx install by default)
  file:
    path: "/etc/nginx/{{ item }}/default"
    state: absent
  become: yes
  loop:
    - sites-enabled
    - sites-available


- name: Remove index.nginx-debian.html (created by nginx install by default)
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
  become: yes


- name: Put data in evoting since the current is not updated
  template:
    src: evoting_nginx.conf
    dest: /etc/nginx/sites-available/evoting
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: yes


#- name: copy TLS key
#  copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
#  notify: restart nginx
#
#
#- name: copy TLS certificate
#  copy: src=files/nginx.crt dest={{ cert_file }}
#  notify: restart nginx


- name: Create symbolic link to evoting nginx
  file:
    src: /etc/nginx/sites-available/evoting
    dest: /etc/nginx/sites-enabled/evoting
    mode: 'u=rwx,g=rx'
    owner: ubuntu
    group: ubuntu
    state: link
  notify: restart nginx
  become: yes


- name: start nginx
  service:
    name: nginx
    state: started
