---
- name: last web-backend tar.gz exists ?
  ansible.builtin.shell:
    cmd: "test -e web-backend-{{ DELA_VERSION }}.tar.gz && echo 'It exists'"
  failed_when: false
  changed_when: false
  register: _web_backend_exist

- name: Download web-backend-v0_4_5-alpha.tar.gz
  ansible.builtin.get_url:
    url: "{{ DELA_GITHUB }}{{ DELA_VERSION_DOT }}/web-backend-{{ DELA_VERSION }}.tar.gz"
    dest: "{{ INSTALL_DIR }}/web-backend-{{ DELA_VERSION }}.tar.gz"
    mode: '0755'
  tags:
    - download_web_backend
  when: _web_backend_exist.stdout.find('It exists') == -1

- name: Unzip last web-backend tar.gz version  # tar xvfz web-backend-v0_4_5-alpha.tar.gz
  ansible.builtin.unarchive:
    src: "web-backend-{{ DELA_VERSION }}.tar.gz"
    dest: /home/ubuntu
    remote_src: yes
  tags:
    - unzip_web_backend
  when: _web_backend_exist.stdout.find('It exists') == -1


- name: Create config.env
  ansible.builtin.template:
    src: config.env
    dest: "web-backend-{{ DELA_VERSION }}/config.env"
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  tags:
    - create_config_env


- name: Remove undefined*  # rm -rf /home/ubuntu/web-backend-{{ DELA_VERSION }}/undefined*
  ansible.builtin.file:
    path: "web-backend-{{ DELA_VERSION }}/undefined*"
    state: absent
  tags:
    - remove_undefined


# AddAdmin is idempotent
- name: Add admins
  shell: |
    NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend-{{ DELA_VERSION }}/dbUtils").addAdmin("data/dvoting-users", 121769)'
    NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend-{{ DELA_VERSION }}/dbUtils").addAdmin("data/dvoting-users", 128871)'

#- name: Add admins
#  shell: |
#    NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend-{{ DELA_VERSION }}/dbUtils").listEls("data/dvoting-users")'
#    NODE_ENV=production PORT=6000 NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node web-backend-{{ DELA_VERSION }}/Server.js
#    NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend-{{ DELA_VERSION }}/dbUtils").addAdmin("data/dvoting-users", 121769)'
#    NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend-{{ DELA_VERSION }}/dbUtils").addAdmin("data/dvoting-users", 128871)'
#    NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend-{{ DELA_VERSION }}/dbUtils").addAdmin("data/dvoting-users")'
#    NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node -e 'require("./web-backend-{{ DELA_VERSION }}/dbUtils").listEls("data/dvoting-users")'
#    NODE_ENV=production PORT=6000 NODE_PATH=web-backend-{{ DELA_VERSION }}/node_modules ./node-{{ NODE_VERSION }}-linux-x64/bin/node web-backend-{{ DELA_VERSION }}/Server.js
