- name: Install web backend
  import_tasks:
    file: ./web_new_versions/web_backend.yml
  tags:
    - install_web_backend



- name: Install web frontend
  import_tasks:
    file: ./web_new_versions/web_frontend.yml
  tags:
    - install_web_frontend

## Useless, since all environment variables are set directly in voting_portal.service
#
#- name: Create config.env
#  ansible.builtin.template:
#    src: config.env
#    dest: "web-backend/config.env"
#    owner: ubuntu
#    group: ubuntu
#    mode: '0755'
#  tags:
#    - create_config_env