- name: Configure app administrators (file 1-add_admin.sh by Linus)
  community.docker.docker_container_exec:
    container: "backend"
    command: "npx cli addAdmin --sciper {{ item }}"
  with_items: "{{ dvoting.admin_scipers }}"
  notify: reload backend
  