---
- name: Include dvoting setup tasks
  tags:
    - dvoting
    - dvoting.setup
  include_tasks:
    file: setup.yml
    apply:
      tags:
        - dvoting
        - dvoting.setup

- name: Include dvoting run tasks
  tags:
    - dvoting
    - dvoting.run
    - dvoting.run.backend
    - dvoting.run.frontend
    - dvoting.run.db
  include_tasks:
    file: run.yml
    apply:
      tags:
        - dvoting
        - dvoting.run

- name: Include configuration tasks
  tags:
    - dvoting
    - dvoting.config
  include_tasks:
    file: config.yml
    apply:
      tags:
        - dvoting
        - dvoting.config

- name: Include dela admin tasks
  tags:
    - dvoting
  include_tasks:
    file: admin.yml
    apply:
      tags:
        - never

