---

# - name: backend docker network
#   community.general.docker_network:
#     name: backend


- name: Run database server
  tags:
    - dvoting.run.db
  community.docker.docker_container:
    name: "postgres"
    hostname: "postgres"
    container_default_behavior: no_defaults
    image: "postgres:15"
    env:
      POSTGRES_USER: "{{ _secrets.db_username }}"
      POSTGRES_PASSWORD: "{{ _secrets.db_password }}"
    restart_policy: 'unless-stopped'
    state: started
    volumes:
      - "{{ dvoting.dbvol }}:/var/lib/postgresql/data"
      - "{{ dvoting.basedir }}/init.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - name: traefik

- name: Run backend web service
  tags:
    - dvoting.run.backend
  community.docker.docker_container:
    name: "backend"
    hostname: "backend"
    container_default_behavior: no_defaults
    image: ghcr.io/c4dt/d-voting-backend:latest
    volumes:
      - "{{ dvoting.bevol }}:/data"
    env:
      DATABASE_USERNAME: "{{ _secrets.db_username }}"
      DATABASE_PASSWORD: "{{ _secrets.db_password }}"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DB_PATH: "/data/dvoting"
      FRONT_END_URL: "{{ dvoting.frontend_url }}"
      DELA_NODE_URL: "{{ dela_node_url }}"
      DELA_PROXY_URL: "{{ dela_proxy_url }}"
      SESSION_SECRET: "{{ _secrets.dvoting_session_secret }}"
      PUBLIC_KEY: "{{ _secrets.PUBLIC_KEY }}"
      PRIVATE_KEY: "{{ _secrets.PRIVATE_KEY }}"
      REACT_APP_DEV_LOGIN: "{{ dvoting.devlogin }}"
      REACT_APP_RANDOMIZE_VOTE_ID: "{{ dvoting.randomize_vote_id }}"
    networks:
      - name: traefik    

- name: Run frontend web service
  tags:
    - dvoting.run.frontend
  community.docker.docker_container:
    name: "frontend"
    hostname: "frontend"
    container_default_behavior: no_defaults
    image: ghcr.io/c4dt/d-voting-frontend:latest
    env:
      FRONT_END_URL: "{{ dvoting.frontend_url }}"
      BACKEND_HOST: "backend"
      BACKEND_PORT: "5000"
      REACT_APP_BLOCKLIST: "{{ hidden_forms | join(',') }}"
    labels:
      traefik.http.services.dvoting_frontend.loadbalancer.server.port: "3000"
      traefik.http.routers.dvoting_frontend.rule: Host("{{ dvoting.frontend_host }}")
      traefik.http.routers.dvoting_frontend.service: dvoting_frontend
      traefik.http.routers.dvoting_frontend.tls: "true"
    networks:
      - name: traefik
      # - name: default

