---

- name: Ensure volumes for database and backend web server
  community.docker.docker_volume:
    name: "dvoting-{{ item }}-data"
  with_items: 
    - database
    - backend

- name: Ensure directory for database init file
  ansible.builtin.file:
    state: directory
    path: "{{ dvoting.basedir }}"
    mode: "755"

- name: Database init file
  ansible.builtin.template:
    src: init.sql
    dest: "{{ dvoting.basedir }}/init.sql"
    mode: "644"
