---
- name: Ensure bin and data directories
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: "{{ ansible_user | default('root') }}"
  with_items:
    - "{{ dela_bin_dir }}"
    - "{{ dela_data_dir }}"
    - "{{ dela_archive }}"

# The following does not work because github requires login
# - name: Install memcoin binary file
#   ansible.builtin.get_url:
#     url: "https://github.com/dedis/d-voting/releases/download/{{ memcoin_bin_version }}/memcoin-linux-amd64-{{ memcoin_bin_version }}"
#     dest: "{{ dela_archive }}/memcoin-linux-amd64-{{ memcoin_bin_version }}"
#     owner: "{{ ansible_user | default('root') }}"
#     mode: "u=rwx,g=rx"
#     force: no # the remote file is versioned therefore does not change

- name: Install memcoin binary
  ansible.builtin.copy:
    src: "vendor/memcoin-linux-amd64-{{ memcoin_bin_version }}"
    dest: "{{ dela_archive }}/memcoin-linux-amd64-{{ memcoin_bin_version }}"
    owner: "{{ ansible_user | default('root') }}"
    mode: "u=rwx,g=rx"

- name: Ensure symlink to current memcoin binary
  ansible.builtin.file:
    state: link
    src: "{{ dela_archive }}/memcoin-linux-amd64-{{ memcoin_bin_version }}"
    path: "{{ memcoin_bin_path }}"

- 